### ISSUE TITLE
hello, I need your help

### ISSUE THREAD

**Issue by sergey-boreysha** [DaveDavenport/libmpd#3]
I'm using your libmpd library in a home project and encountered a problem getting elapsed time:

elapsed_time = mpd_status_get_elapsed_song_time(obj);

the sound from the speakers does not coincide with the program's response in time

what could this be connected with?

**Comment by DaveDavenport** [comment]
libmpd is not really maintained anymore. 

The result from this commands comes from MPD, so if the elapsed time is wrong its either mpd (most likely the library that mpd uses to get the song info/play it).

Try using mpc to validate if it is libmpd or mpd provides the wrong information.
